// ============================================================
// ARETE — Beslenme Veritabanı
// ============================================================

export const BESLENME_DB = {

  // ─── 🍳 KAHVALTILIKLAR VE HAMUR İŞLERİ ─────────────────
  kahvaltilik: [
    {
      name: "Peynirli Krep",
      icerik: "Krep hamuru, peynir, yumurta (E: 3 tam, K: 1 tam), zeytin, ceviz içi, yeşillik.",
      youtube: "https://youtu.be/RVYTQwQH7r0?si=1dTbpXpNAuNJf-bW",
      erkek: { kcal: 517, p: 37, c: 13, y: 34 },
      kadin: { kcal: 343, p: 24, c: 12, y: 22 },
    },
    {
      name: "Yulaflı Tost",
      icerik: "Yulaf, yumurta, light kaşar peyniri (E: 40g, K: 30g), zeytin ve yeşillik.",
      youtube: "https://youtu.be/VOgtX6zXUrl",
      erkek: { kcal: 550, p: 46, c: 22, y: 24 },
      kadin: { kcal: 417, p: 30, c: 20, y: 18 },
    },
    {
      name: "Burrito",
      icerik: "Tam buğday lavaş, yumurta (E: 4, K: 2), zeytinyağı, light kaşar, hindi füme, domates, yeşillik.",
      youtube: "https://youtu.be/3ye-kIPAn3A",
      erkek: { kcal: 664, p: 59, c: 34, y: 30 },
      kadin: { kcal: 430, p: 33, c: 36, y: 18 },
    },
    {
      name: "Tuzlu Pankek",
      icerik: "Yumurta, yoğurt, yulaf unu, yarım yağlı peynir, maydanoz, hindi füme, zeytin/kuruyemiş.",
      youtube: "https://youtu.be/HDZyAufhAcs",
      erkek: { kcal: 506, p: 38, c: 43, y: 20 },
      kadin: { kcal: 330, p: 22, c: 34, y: 13 },
    },
    {
      name: "Tavada Pizza",
      icerik: "Yumurta, tam buğday unu, yoğurt, salça, kekik, hindi füme, light kaşar, zeytin.",
      youtube: "https://youtu.be/b9XoRQGcbd8",
      erkek: { kcal: 525, p: 56, c: 27, y: 17 },
      kadin: { kcal: 364, p: 26, c: 25, y: 13 },
    },
    {
      name: "Fırında Yumurtalı Ekmek",
      icerik: "Hindi füme, yumurta, light kaşar, domates, ekstra omlet (sadece erkekler için).",
      youtube: "https://youtu.be/z_IKoApCzYg",
      erkek: { kcal: 450, p: 48, c: 22, y: 18 },
      kadin: { kcal: 338, p: 32, c: 21, y: 13 },
    },
    {
      name: "Oopsie Ekmeği",
      icerik: "Lor peyniri, yumurta beyazı, yanına süzme peynir, tahin-pekmez.",
      youtube: "https://youtu.be/J3nlJjAfE5A",
      erkek: { kcal: 614, p: 53, c: 31, y: 34 },
      kadin: { kcal: 377, p: 30, c: 23, y: 19 },
    },
    {
      name: "Ispanaklı Omlet",
      icerik: "Yumurta (E: 6, K: 3), hindi füme, ıspanak, lor peyniri, zeytin.",
      youtube: "https://youtu.be/wvWkSJgH708",
      erkek: { kcal: 515, p: 44, c: 17, y: 22 },
      kadin: { kcal: 382, p: 28, c: 15, y: 17 },
    },
    {
      name: "Pırasalı Tava Böreği",
      icerik: "Pırasa, yumurta, tuzsuz yağsız lor peyniri, zeytin.",
      youtube: "https://youtu.be/y5WkrZR90L0",
      erkek: { kcal: 534, p: 47, c: 38, y: 26 },
      kadin: { kcal: 459, p: 34, c: 33, y: 21 },
    },
    {
      name: "Omlet Sandviç",
      icerik: "Kızarmış tam buğday ekmeği, light kaşar, yumurta (E: 4, K: 3), zeytinyağı, zeytin.",
      youtube: "https://youtu.be/D4Fmq1YMcGw",
      erkek: { kcal: 522, p: 46, c: 14, y: 29 },
      kadin: { kcal: 341, p: 30, c: 12, y: 17 },
    },
    {
      name: "Sebzeli Omlet / Tatlı Pancake Karışımı",
      icerik: "Muzlu pancake (yumurta + muz), lor peyniri, fıstık ezmesi.",
      youtube: "https://youtu.be/QOvJxfs-1D0",
      erkek: { kcal: 621, p: 47, c: 38, y: 31 },
      kadin: { kcal: 416, p: 25, c: 34, y: 21 },
    },
    {
      name: "Karabuğday Patlağı (Ev Yapımı)",
      icerik: "Karabuğday patlağı (E: 6 adet, K: 4 adet), badem, whey protein (E).",
      youtube: "https://youtu.be/i1i2naxFOIM?si=ufvGAF_v818wOEKS",
      erkek: { kcal: 554, p: 37, c: 76, y: 16 },
      kadin: { kcal: 360, p: 10, c: 50, y: 16 },
    },
  ],

  // ─── 🍲 ANA YEMEKLER VE TAVALAR ─────────────────────────
  anaYemek: [
    {
      name: "Tepsi Kebabı",
      icerik: "Yağsız et (E: 300g, K: 200g), sebzeler, zeytinyağlı salata.",
      youtube: "https://youtu.be/lTe4r1odzyk",
      erkek: { kcal: 754, p: 73, c: 48, y: 29 },
      kadin: { kcal: 615, p: 52, c: 48, y: 23 },
    },
    {
      name: "Kıymalı Karnabahar",
      icerik: "Az yağlı kıyma (E: 250g, K: 150g), karnabahar, salata.",
      youtube: "https://youtu.be/RiQhuCrSB3M",
      erkek: { kcal: 752, p: 66, c: 46, y: 36 },
      kadin: { kcal: 613, p: 45, c: 46, y: 30 },
    },
    {
      name: "Beyaz Etli Karnabahar (Fırın)",
      icerik: "Çiğ beyaz et (E: 300g, K: 200g), karnabahar, yoğurt.",
      youtube: "https://youtu.be/ZQrV5ZsGBfc",
      erkek: { kcal: 704, p: 88, c: 40, y: 22 },
      kadin: { kcal: 519, p: 61, c: 39, y: 14 },
    },
    {
      name: "Fırın Karnabahar",
      icerik: "Karnabahar, lor peyniri, yeşil mercimek (sadece erkeklere), salata.",
      youtube: "https://youtu.be/awCin7P1ZN4",
      erkek: { kcal: 612, p: 40, c: 58, y: 24 },
      kadin: { kcal: 520, p: 34, c: 42, y: 24 },
    },
    {
      name: "Kıymalı Kapuska",
      icerik: "Yağsız kıyma (E: 300g, K: 150g), lahana, salata.",
      youtube: "https://youtu.be/VFgPwoEdRU4",
      erkek: { kcal: 776, p: 71, c: 30, y: 38 },
      kadin: { kcal: 582, p: 39, c: 30, y: 31 },
    },
    {
      name: "Kıymalı Nohut",
      icerik: "Yağsız kıyma, nohut, salata.",
      youtube: "https://youtu.be/0siBrUTFVr4",
      erkek: { kcal: 720, p: 68, c: 56, y: 25 },
      kadin: { kcal: 615, p: 47, c: 56, y: 21 },
    },
    {
      name: "Et Tantuni",
      icerik: "Yağsız et (E: 300g, K: 200g), tek lavaş, ayran.",
      youtube: "https://youtu.be/OYcinbbdyu",
      erkek: { kcal: 754, p: 73, c: 37, y: 32 },
      kadin: { kcal: 618, p: 52, c: 37, y: 27 },
    },
    {
      name: "Tavuk Quesadilla",
      icerik: "Tavuk göğsü (E: 300g, K: 200g), lavaş, ayran/kefir.",
      youtube: "https://youtu.be/aK9YXfm2gm4",
      erkek: { kcal: 701, p: 88, c: 28, y: 27 },
      kadin: { kcal: 581, p: 65, c: 28, y: 24 },
    },
    {
      name: "Ev Yapımı Izgara Köfte",
      icerik: "Yağsız kıymadan köfte (E: 7 adet, K: 5 adet), kinoa kısırı, yoğurt.",
      youtube: "https://youtu.be/HRU5W4tyZrw",
      erkek: { kcal: 750, p: 50, c: 41, y: 32 },
      kadin: { kcal: 489, p: 38, c: 26, y: 24 },
    },
    {
      name: "Lor Köftesi",
      icerik: "Lor köftesi, haşlanmış yeşil mercimek, yoğurt, salata.",
      youtube: "https://youtu.be/rttfy3bcUXY",
      erkek: { kcal: 700, p: 42, c: 55, y: 30 },
      kadin: { kcal: 540, p: 32, c: 48, y: 26 },
    },
    {
      name: "Fırında Pancarlı Somon",
      icerik: "Somon (E: 250/300g, K: 150/200g), pancar, salata.",
      youtube: "https://youtu.be/Z1fUZakahwU",
      erkek: { kcal: 737, p: 51, c: 41, y: 41 },
      kadin: { kcal: 569, p: 33, c: 39, y: 32 },
    },
    {
      name: "Mantar Sote",
      icerik: "Mantar, lor peynirli salata, yoğurt.",
      youtube: "https://youtu.be/s7fs2TLGHIg",
      erkek: { kcal: 667, p: 33, c: 69, y: 33 },
      kadin: { kcal: 560, p: 28, c: 58, y: 28 },
    },
    {
      name: "Tavuklu Makarna",
      icerik: "Beyaz et (E: 300g, K: 200g), kuru makarna (E: 50g, K: 30g), zeytinyağlı salata.",
      youtube: "https://youtu.be/27i1Xu8llfA",
      erkek: { kcal: 749, p: 86, c: 62, y: 19 },
      kadin: { kcal: 573, p: 59, c: 47, y: 18 },
    },
    {
      name: "Erişteli Mercimek Yemeği",
      icerik: "Beyaz et, erişte/mercimek, salata.",
      youtube: "https://youtu.be/k7YDiwORSow",
      erkek: { kcal: 710, p: 86, c: 42, y: 22 },
      kadin: { kcal: 521, p: 55, c: 41, y: 15 },
    },
    {
      name: "Bal Kabağı / Brokoli Çorbası",
      icerik: "Çorba (bal kabağı veya brokoli), beyaz et (E: 300g, K: 200g), pancar salatası.",
      youtube: "https://youtu.be/7pExUXRUOMg",
      erkek: { kcal: 666, p: 96, c: 36, y: 14 },
      kadin: { kcal: 486, p: 66, c: 28, y: 12 },
    },
    {
      name: "Ispanak Beğendi",
      icerik: "Ispanak püresi, beyaz et sote (E: 350g, K: 200g), salata.",
      youtube: "https://youtu.be/tl-8A8KuFdQ",
      erkek: { kcal: 698, p: 99, c: 22, y: 24 },
      kadin: { kcal: 537, p: 62, c: 22, y: 22 },
    },
    {
      name: "Ispanak Böreği",
      icerik: "Ispanak böreği, protein tozu/muz (E).",
      youtube: "https://youtu.be/j2pcJXKNNeU",
      erkek: { kcal: 507, p: 49, c: 35, y: 23 },
      kadin: { kcal: 318, p: 24, c: 15, y: 21 },
    },
  ],

  // ─── 🥗 BOWLLAR VE SALATALAR ────────────────────────────
  bowl: [
    {
      name: "Tavuk Göğüs Bowl",
      icerik: "Izgara tavuk göğsü (E: 300g, K: 200g), basmati pirinç, haşlanmış nohut.",
      youtube: "https://youtu.be/UbEzU7vnhel?si=T0OP-F6nK5PkF6_h",
      erkek: { kcal: 789, p: 73, c: 47, y: 28 },
      kadin: { kcal: 615, p: 50, c: 35, y: 27 },
    },
    {
      name: "Kıyma Bowl",
      icerik: "Az yağlı kıyma (E: 250g, K: 150g), haşlanmış çiğ fasulye.",
      youtube: "https://youtu.be/A21YRYcdBzl?si=R20Kh5DP0SgV04Tg",
      erkek: { kcal: 806, p: 70, c: 51, y: 36 },
      kadin: { kcal: 602, p: 45, c: 25, y: 29 },
    },
    {
      name: "Ton Balıklı Nohutlu Salata",
      icerik: "Ton balığı, haşlanmış nohut, mısır, zeytinyağı, ceviz.",
      youtube: "https://youtu.be/di7YLF4UomY",
      erkek: { kcal: 618, p: 65, c: 36, y: 24 },
      kadin: { kcal: 543, p: 62, c: 28, y: 20 },
    },
    {
      name: "Kahvaltılık Salata",
      icerik: "Haşlanmış yumurta, lor peyniri, esmer ekmek.",
      youtube: "https://youtu.be/XwOJ5KtZcdc?si=0iHmgInjFyYLmpCf",
      erkek: { kcal: 493, p: 34, c: 32, y: 28 },
      kadin: { kcal: 374, p: 11, c: 30, y: 26 },
    },
    {
      name: "Yumurta Salatası",
      icerik: "Yumurta (tam + beyaz), wasa/kızarmış ekmek, light kaşar.",
      youtube: "https://youtu.be/YaRsDo23DEo",
      erkek: { kcal: 517, p: 53, c: 13, y: 28 },
      kadin: { kcal: 354, p: 31, c: 12, y: 20 },
    },
    {
      name: "Ton Balıklı Sandviç",
      icerik: "Esmer ekmek, ton balığı, salata, whey (E).",
      youtube: "https://youtu.be/G4cI3LohvIk?si=1usQDH4J3-s6VO95",
      erkek: { kcal: 564, p: 62, c: 55, y: 11 },
      kadin: { kcal: 335, p: 21, c: 15, y: 21 },
    },
  ],

  // ─── 🍪 TATLILAR VE ATIŞTIRMALIKLAR ─────────────────────
  tatli: [
    {
      name: "Muzlu Browni",
      icerik: "Muzlu fit browni (E: 5 adet, K: 3 adet), kuruyemiş, whey protein (E).",
      youtube: "https://youtu.be/BDawiNMQnzU",
      erkek: { kcal: 511, p: 38, c: 47, y: 21 },
      kadin: { kcal: 307, p: 11, c: 28, y: 18 },
    },
    {
      name: "Nohutlu Browni",
      icerik: "Nohutlu browni, badem, protein tozu (E).",
      youtube: "https://youtu.be/hhzza4D3jjU",
      erkek: { kcal: 526, p: 36, c: 43, y: 23 },
      kadin: { kcal: 277, p: 9, c: 27, y: 15 },
    },
    {
      name: "Tatlı Patates Browni",
      icerik: "Tatlı patates bazlı browni, badem/whey.",
      youtube: "https://youtu.be/jfpLHd3Ex94?si=bD_cURvfXIoAJ4ju",
      erkek: { kcal: 594, p: 37, c: 77, y: 16 },
      kadin: { kcal: 355, p: 9, c: 46, y: 15 },
    },
    {
      name: "Sütlü İrmik Tatlısı",
      icerik: "İrmik, süt, muz, çilek, badem.",
      youtube: "https://youtu.be/5fehiAyY8aY",
      erkek: { kcal: 400, p: 26, c: 35, y: 17 },
      kadin: { kcal: 250, p: 20, c: 34, y: 4 },
    },
    {
      name: "Yalancı Tiramisu",
      icerik: "Fit tiramisu, badem, whey protein (E).",
      youtube: "https://youtu.be/IrdUoK0pyPo",
      erkek: { kcal: 532, p: 41, c: 36, y: 24 },
      kadin: { kcal: 279, p: 12, c: 34, y: 10 },
    },
    {
      name: "Leblebi Tatlısı",
      icerik: "Leblebi unu tatlısı (E: 5 adet, K: 3 adet).",
      youtube: "https://youtu.be/hNwEZEin0KQ?si=DkG16wx-j1U8gYVQ",
      erkek: { kcal: 482, p: 18, c: 68, y: 13 },
      kadin: { kcal: 289, p: 11, c: 41, y: 8 },
    },
    {
      name: "Coco Star",
      icerik: "Fit coco star (E: 4 adet, K: 3 adet), shake.",
      youtube: "https://youtu.be/eVF22IjA-TM",
      erkek: { kcal: 547, p: 30, c: 38, y: 33 },
      kadin: { kcal: 321, p: 5, c: 28, y: 24 },
    },
    {
      name: "Fıstık Ezmeli Bar",
      icerik: "Fıstık ezmesi barı, whey.",
      youtube: "https://youtu.be/nipxoVPOqo0",
      erkek: { kcal: 568, p: 48, c: 27, y: 31 },
      kadin: { kcal: 416, p: 29, c: 20, y: 24 },
    },
    {
      name: "Protein Bar",
      icerik: "Ev yapımı protein bar, whey.",
      youtube: "https://youtu.be/xwGn2VmVASK",
      erkek: { kcal: 467, p: 38, c: 35, y: 20 },
      kadin: { kcal: 348, p: 14, c: 34, y: 18 },
    },
    {
      name: "Tahinli Kurabiye",
      icerik: "Tahinli kurabiye (E: 7 adet, K: 4 adet), whey.",
      youtube: "https://youtu.be/VA--AUDAzMg",
      erkek: { kcal: 563, p: 41, c: 51, y: 20 },
      kadin: { kcal: 296, p: 11, c: 33, y: 12 },
    },
    {
      name: "Tuzlu Yulaflı Kurabiye",
      icerik: "Yulaflı kurabiye (E: 10 adet, K: 5 adet), yeşil çay, protein tozu.",
      youtube: "https://youtu.be/ah96-gpxbXA",
      erkek: { kcal: 624, p: 47, c: 46, y: 24 },
      kadin: { kcal: 307, p: 15, c: 29, y: 14 },
    },
    {
      name: "Şekersiz Yulaf Topları",
      icerik: "Yulaf topları (E: 5 adet, K: 4 adet), ceviz içi.",
      youtube: "https://youtu.be/abxzAqlJnhQ",
      erkek: { kcal: 462, p: 34, c: 39, y: 18 },
      kadin: { kcal: 294, p: 9, c: 30, y: 16 },
    },
    {
      name: "Banana Bread",
      icerik: "Muzlu ekmek, ceviz, meyve/whey blend (E).",
      youtube: "https://youtu.be/eKJbHtUcK40",
      erkek: { kcal: 556, p: 37, c: 52, y: 24 },
      kadin: { kcal: 359, p: 22, c: 21, y: 19 },
    },
    {
      name: "Chia Puding",
      icerik: "Süt, chia tohumu, protein tozu/bal, muz, badem.",
      youtube: "https://youtu.be/vRRyvchreMk",
      erkek: { kcal: 544, p: 53, c: 21, y: 26 },
      kadin: { kcal: 282, p: 27, c: 12, y: 14 },
    },
  ],

  // ─── 🌱 VEGAN ÖZEL TARİFLERİ ────────────────────────────
  vegan: [
    {
      name: "Vegan Tahıl Salata",
      icerik: "Kuru börülce, maş fasulyesi, beluga mercimeği, yeşil mercimek, avokado, ceviz, zeytinyağı.",
      youtube: null,
      erkek: { kcal: 1000, p: 36, c: 57, y: 70 },
      kadin: { kcal: 750, p: 29, c: 45, y: 53 },
    },
    {
      name: "Domatesli Mantarlı Krep",
      icerik: "Badem unu, bitkisel süt, tofu peyniri, zeytin, yeşillik.",
      youtube: null,
      erkek: { kcal: 380, p: 22, c: 14, y: 25 },
      kadin: { kcal: 290, p: 16, c: 13, y: 19 },
    },
    {
      name: "Badem Unlu Pankek",
      icerik: "Badem unu, bitkisel süt, muz, fıstık ezmesi.",
      youtube: null,
      erkek: { kcal: 605, p: 24, c: 24, y: 50 },
      kadin: { kcal: 435, p: 25, c: 25, y: 17 },
    },
    {
      name: "Vegan Tam Buğday Spaghetti",
      icerik: "Tam buğday spaghetti, vegan peynir, mantar, biber, domates, pesto sos, avokado.",
      youtube: null,
      erkek: { kcal: 745, p: 20, c: 50, y: 55 },
      kadin: { kcal: 690, p: 19, c: 45, y: 50 },
    },
    {
      name: "Havuçlu Kereviz Yemeği & Siyah Pirinç",
      icerik: "Havuçlu kereviz yemeği, siyah pirinç pilavı, yeşillikli salata.",
      youtube: null,
      erkek: { kcal: 650, p: 35, c: 74, y: 33 },
      kadin: { kcal: 500, p: 13, c: 63, y: 22 },
    },
    {
      name: "Kabak Spaghetti",
      icerik: "Kabak spaghetti, zeytinyağlı domates sosu, mantar sote, avokado.",
      youtube: null,
      erkek: { kcal: 330, p: 10, c: 5, y: 30 },
      kadin: { kcal: 320, p: 9, c: 4, y: 30 },
    },
    {
      name: "Sebzeli Mantar Sote & Karabuğday",
      icerik: "Mantar sote, haşlanmış karabuğday, zeytinyağlı salata.",
      youtube: null,
      erkek: { kcal: 1175, p: 30, c: 128, y: 60 },
      kadin: { kcal: 931, p: 25, c: 100, y: 48 },
    },
  ],
};
